# Generated by Django 3.2.13 on 2023-01-16 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImg', models.CharField(default='', max_length=50, verbose_name='profileImg')),
                ('writeDate', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=50)),
                ('content', models.TextField(max_length=300)),
                ('imageList', models.JSONField(blank=True, verbose_name='imageList')),
                ('likeCount', models.IntegerField(default=0, verbose_name='likeCount')),
                ('commentCount', models.IntegerField(default=0, verbose_name='commentCount')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=30)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('theme', models.CharField(default='', max_length=20)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel', to='community.board')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeName', models.CharField(default='대구', max_length=20)),
                ('saveDate', models.DateTimeField()),
                ('memo', models.CharField(max_length=20)),
                ('placeImgList', models.JSONField(blank=True, verbose_name='placeImgList')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('address', models.CharField(default='', max_length=40)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeList', to='community.travel')),
            ],
        ),
    ]
