# Generated by Django 3.2.13 on 2023-01-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='theme',
        ),
        migrations.AddField(
            model_name='board',
            name='theme',
            field=models.CharField(default='', max_length=20),
        ),
    ]
