# Generated by Django 3.2.13 on 2023-01-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imagelist',
            table=None,
        ),
    ]
