# Generated by Django 3.2.13 on 2023-01-13 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_community_travel_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='Community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='community.community'),
        ),
    ]
