# Generated by Django 3.2.13 on 2023-02-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20230208_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='placeImgList',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='PlaceImage',
        ),
    ]
