# Generated by Django 3.2.13 on 2023-01-17 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_imagelist_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagelist',
            name='place',
        ),
        migrations.AlterField(
            model_name='imagelist',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageList', to='community.board'),
        ),
    ]
