# Generated by Django 3.2.13 on 2023-02-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_board_likelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, default='2023-02-05 15:01:19.194416'),
            preserve_default=False,
        ),
    ]
