# Generated by Django 3.2.13 on 2023-01-17 13:47

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20230117_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelist',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='profile_image/boards/%Y/%m'),
        ),
    ]
