# Generated by Django 3.2.13 on 2023-02-08 15:17

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20230208_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='placeImgList',
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='palce_image/%Y/%m')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeImgList', to='community.place')),
            ],
        ),
    ]
