# Generated by Django 3.2.13 on 2023-01-17 15:49

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_imagelist_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='profile_image/place/%Y/%m')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeImgList', to='community.place')),
            ],
        ),
    ]
