# Generated by Django 3.2.13 on 2023-01-28 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0006_auto_20230127_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='commentCount',
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentList', to=settings.AUTH_USER_MODEL),
        ),
    ]
