# Generated by Django 3.2.13 on 2023-01-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=15, verbose_name='age'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='Ghost', max_length=50, verbose_name='nickname'),
            preserve_default=False,
        ),
    ]
