# Generated by Django 3.2.13 on 2023-01-19 09:56

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImg', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='profile_image/accounts/%Y/%m')),
            ],
        ),
    ]
