# Generated by Django 3.2.13 on 2023-02-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='naver',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='naver_email'),
        ),
    ]
