# Generated by Django 3.2.13 on 2023-01-09 07:11

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='google_email'),
        ),
        migrations.AddField(
            model_name='user',
            name='kakao_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='kakao_email'),
        ),
        migrations.AddField(
            model_name='user',
            name='naver_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='naver_email'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=1, max_length=13, verbose_name='phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='profile_image/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email_address'),
        ),
    ]
