# Generated by Django 3.2.13 on 2023-02-06 16:23

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230206_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileImg',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile_image/accounts/%Y/%m'),
        ),
    ]
