version: "3.0"                                                # docker-compose 버전이다
services:                                                   
    db:                                                     
        image: mysql                                
        container_name: mysql01                            
        environment:
            MYSQL_DATABASE: django_mobile                                   
            MYSQL_ROOT_PASSWORD: sangjun1324 
                                                     
    web:                                                
        build: .                           # 메인으로 빌드될 Dockerfile을 적는다. 지금은 현재 폴더에 있다고 알린다
        container_name: dg01                                
        command: > 
            bash -c "python3 manage.py collectstatic --no-input &&   
            python3 manage.py makemigrations &&             
            python3 manage.py migrate &&                    
            gunicorn pjtback.wsgi:application -b 0:80"
        depends_on:                                         
            - db
        links:
            - db                                            
        volumes:                                            
            - .:/pjtback
    nginx:                                                                                    
        image: nginx                             
        container_name: ng01
        ports:                                              # 포트 개방 "hostPort:dockerPort"으로 포워딩한다
            - "80:80"                                       
        volumes:                                            # 볼륨 마운트. 호스트의 파일을 사용하려면 필요하다                             
            - .:/pjtback                                      
            - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf # nginx 세팅 마운트
        depends_on:  
            - web                                     


